name: Latest blog post workflow v2

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update this repo‚Äôs README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in Tistory posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://prao.tistory.com/rss"
          accept_header: "text/xml"
          max_post_count: 5
          date_format: "yyyy.MM.dd"
          item_exec: "decodeURI"
          template: |
            <div align="center">
              <h3>üçä Tistory üçä</h3>
              <table>
                <thead>
                  <tr>
                    <th>ÎÇ†Ïßú</th>
                    <th>Ï†úÎ™©</th>
                  </tr>
                </thead>
                <tbody>
                  {{#each items}}
                  <tr>
                    <td>{{date}}</td>
                    <td><a href="{{url}}">{{title}}</a></td>
                  </tr>
                  {{/each}}
                </tbody>
              </table>
            </div>
