name: Latest blog post workflow

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update this repo’s README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in Tistory posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://prao.tistory.com/rss"
          accept_header: "text/xml"
          max_post_count: 5
          date_format: "yyyy.MM.dd"
          item_exec: "decodeURI"
          template: |
            | 날짜 | 제목 |
            |------|------|
            {{#each items}}
            | {{date}} | [{{title}}]({{url}}) |
            {{/each}}

