name: Latest blog post workflow

on:
  schedule:
    - cron: '0 * * * *' # ë§¤ì‹œ ì •ê°ë§ˆë‹¤ ì‹¤í–‰
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in Tistory posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://prao.tistory.com/rss"
          accept_header: "application/rss+xml"
          max_post_count: 5
          date_format: "yyyy.MM.dd"
          disable_html_encoding: true
          commit_message: "ğŸ§© Updated Tistory section"
          template: |
            | ë‚ ì§œ | ì œëª© |
            |------|------|
            $newline
            $emojiKey(ğŸ§©,ğŸ“˜,ğŸ’¡,ğŸª„,ğŸš€)
            $counter. $date | [$title]($url)
            $newline
